services:
  app:
    image: client
    container_name: client
    build:
      context: ./frontend
      dockerfile: Dockerfile

  auth-server:
    image: auth-server
    container_name: auth-server
    build:
      context: ./backend/auth-server
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  graphql-server:
    image: graphql-server
    container_name: graphql-server
    build:
      context: ./backend/graphql-server
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - auth-server
      - graphql-server
